server:
  port: 8002
spring:
  application:
    name: service_oss
  profiles:
    active: dev
aliyun:
  oss:
    end-point: oss-cn-beijing.aliyuncs.com
    access-key-id: “Access Key”
    access-key-secret: “Access secret”
    bucket-name: sport-club
